development:
  adapter: postgresql
  database: sj_development
  host: localhost

test:
  adapter: postgresql
  database: sj_test
  host: localhost

production:
  adapter: postgresql
  database: sj_production
  host: localhost